### ISSUE TITLE
cannot import name utils

### ISSUE THREAD

**Issue by wt123u** [vered1986/UnsupervisedHypernymy#1]
Hi, @vered1986  
It's something wrong with  the module of source/dsm_creation/common.py , In line 7 .  I want to know that the composes is a tool or the module writing by you ? I don' t know  whether  it is the version problem , it can't install the package.

**Comment by esantus** [comment]
Hi,

You can find it here:

http://clic.cimec.unitn.it/composes/toolkit/introduction.html

Best,
Enrico
