### ISSUE TITLE
About frequency_file

### ISSUE THREAD

**Issue by fengchangc** [vered1986/UnsupervisedHypernymy#3]
Hi, @vered1986 

What's the format of <frequency_file> in your code source/dsm_creation/create_joint_dep_based_cooc_file.py? Does it need to be calculated according to the input corpus by myself? 
By the way, can I know which format of UKWac dataset are u using? I found a POS-tagged version and a NON-POS-tagged version. Is it okay to use only plain text as input?

Thanks a lot!

**Comment by vered1986** [comment]
Hi,

It's a text file with one word per line, containing the words that appear at least 100 times in the corpus. You can get it from [here](https://drive.google.com/file/d/1lo0w6k4wDz-IGkHTuotcCJJW9_itSEkE/view?usp=sharing). 

We used the POS-tagged and parsed version. I'm not sure our scripts would work on the plain text format (for window based DSMs), and you certainly need the parsed format to build a dependency-based DSM.
