### ISSUE TITLE
what is 'composes'?

### ISSUE THREAD

**Issue by zjk000** [vered1986/UnsupervisedHypernymy#5]
Hello, I am trying to run source/dsm_creation/create_dsm.py, in which some tools are imported from this package 'composes', the thing is, I can't find this package 'composes'  neither on Google nor on Bing, or install it directly using 'pip install composes', is it a publicly available package?

**Comment by vered1986** [comment]
We used this package: https://marcobaroni.org/composes/toolkit/index.html

Apologies from my past self about the poor documentation :) 

I'm not sure this package is available for installation on pip, or even whether it's still supported in Python 3.
